- name : demo on prinint variable from play level
  hosts : all
  vars :
    URL : play.variable.com
  tasks:
    - name : print the play variable
      ansible.builtin.debug:
        msg : URL - {{ URL }}

  tasks:
    - name : print the play variable1
      ansible.builtin.debug:
        msg : URL - {{ URL }}


- name : Load variable from files
  hosts : all
  vars_files :
    - file1.yml
  tasks:
    - name : print the file variable
      ansible.builtin.debug:
        msg : URL - {{ URL }}


- name : Demo on Task variable
  hosts : all
  tasks :
    - name : print the task variable
      ansible.builtin.debug:
        msg : URL - {{ URL }}
      vars :
        URL : task.variable.com

- name : demo on role variables
  hosts : all
  vars :
    URL_PLAY : role.play_variable.com
  roles:
    - sample

- name : demo on register variables
  hosts : all
  tasks :
    - name : store shell command
      ansible.builtin.shell: uptime
      register : output
    - name : print the output
      ansible.builtin.debug:
        msg : "{{ output.stdout }}"

