- name : demo on prinint variable from play level
  hosts : all
  vars :
    URL : play.variable.com
  tasks:
    - name : print the play variable
      ansible.builtin.debug:
        msg : URL - {{ URL }}